[requirement]
min_version = [0,36,4]

[general]
reload_config_each_move = false
clear_hash_after_config_loaded = false
default_thread_num = 1
message_mode = "normal"
coord_conversion_mode = "X_flipY"
default_candidate_range = "square3_line4"
memory_reserved_mb = 0
default_tt_size_kb = 16384


[model]
[model.eval]
model_type = 2
table2 = [
0,	0,	0,	0,	0,	0,	0,	0,	0,	0,	0,	0,	36,	41,
	0,	0,	0,	0,	0,	0,	0,	0,	0,	0,	0,	36,	41,
		0,	0,	0,	1,	1,	1,	2,	9,	9,	16,	36,	41,
			0,	0,	1,	1,	1,	2,	10,	10,	17,	38,	43,
				1,	2,	2,	2,	3,	11,	11,	19,	39,	44,
					3,	3,	3,	4,	13,	13,	20,	42,	47,
						3,	3,	4,	13,	13,	20,	42,	47,
							3,	4,	13,	13,	20,	42,	47,
								5,	14,	14,	22,	43,	49,
									25,	25,	34,	57,	62,
										25,	34,	57,	62,
											43,	67,	72,
												93,	99,
													105
]

[model.eval.renju]
model_type = 2
table2 = [
0,	0,	0,	0,	0,	1,	1,	1,	2,	9,	9,	15,	36,	40,
	0,	0,	0,	0,	1,	1,	1,	2,	9,	9,	15,	36,	40,
		0,	0,	0,	1,	1,	1,	2,	9,	9,	15,	36,	40,
			0,	0,	1,	1,	1,	2,	9,	9,	15,	37,	40,
				1,	2,	2,	2,	3,	10,	10,	17,	38,	42,
					3,	3,	3,	4,	12,	12,	18,	40,	44,
						3,	3,	4,	12,	12,	18,	40,	44,
							3,	4,	12,	12,	18,	40,	44,
								5,	13,	13,	20,	42,	46,
									23,	23,	30,	54,	58,
										23,	30,	54,	58,
											38,	63,	67,
												90,	94,
													99
]

[model.score]
[model.score.self]
model_type = 1
table1 = [-1,0,0,1,2,6,6,6,9,16,20,30,100,500]
table1_scale = 2.0

[model.score.oppo]
model_type = 1
table1 = [-1,0,0,1,2,6,6,6,9,16,20,30,100,500]
table1_scale = 1.0


[search]
aspiration_window = false
num_iteration_after_mate = 16
num_iteration_after_singular_root = 10


[search.timectl]
match_space = 21.0
match_space_min = 7.0
average_branch_factor = 1.7
advanced_stop_ratio = 0.9
move_horizon = 64
